### ISSUE TITLE
character error

### ISSUE THREAD

**Issue by HerculesNode** [base-org/node#124] opened 2023-10-06 19:58 UTC
https://github.com/base-org/node/blob/v0.3.2/docker-compose.yml#L5

found in the docker-compose file

In line 5 and line 19, the ( . ) sign after the build : tag breaks the configuration.

**Comment by mdehoog** [comment] 2023-10-06 20:01
the `.` means to build the local `Dockerfile`. Do you have the full repo checked out, and the latest docker / docker-compose installed? what error are you seeing?

**Comment by HerculesNode** [comment] 2023-10-06 20:17
Dockerfile yeah sory.

https://github.com/base-org/node/blob/v0.3.2/op-node-entrypoint#L5

node-node-1  | ./op-node-entrypoint: 5: [: Illegal number:

**Comment by mdehoog** [comment] 2023-10-06 20:23
Oh thank you for the report, this is a duplicate of #122, which was fixed in #123 and released in `v0.3.3`.

**Closed by mdehoog** 2023-10-06 20:23 UTC
Labels: minor, type: bug, type: question, state: investigation
