### ISSUE TITLE
add blob archiver flag for synchronizing nodes that are older than 18 days. ethereum-optimism/optimism#9992  op-node 

### ISSUE THREAD

**Issue by melai278** [base-org/node#270] opened 2024-06-06 14:48 UTC
ADDITIONAL_ARGS=""

if [ "${OP_NODE_L1_BLOB_ARCHIVER+x}" = x ]; then
    ADDITIONAL_ARGS="$ADDITIONAL_ARGS --l1.beacon-archiver=$OP_NODE_L1_BLOB_ARCHIVER"
fi

....

exec ./op-node \
   $ADDITIONAL_ARGS

**Comment by roberto-bayardo** [comment] 2024-06-07 14:50
would recommend specifying this in your .env.mainnet file to avoid modifying the entrypoint file.

**Comment by wbnns** [comment] 2024-06-08 02:16
Closing, duplicate of #268

**Closed by wbnns** 2024-06-08 02:16 UTC
